tasks:
  - command: |
      curl -fsSL https://get.pulumi.com | sh
      # Amazon CLI:
      # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # unzip awscliv2.zip
      # sudo ./aws/install